Description: >
  Project - Deploy infrastructure for Omdena project "WRI Latinamerica"
  Author - Susanne Brockmann

  Setting up the servers

Parameters:
     EnvironmentName:
         Description: Env Name that will be prefixed in order to access variables exported in the stack from infrastructure.yml
         Type: String


Resources:
  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow http 
      VpcId: 
          Fn::ImportValue:
            !Sub "${EnvironmentName}-VPCID"
      GroupName: Security Group for WebServer internal traffic
      SecurityGroupEgress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 0
          ToPort: 65535
          IpProtocol: tcp
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          ToPort: 80
          IpProtocol: tcp
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22
          IpProtocol: tcp


  SeverInstance:
    Type: AWS::EC2::Instance
    Properties:
      #ImageId: ami-00831fc7c1e3ddc60 # Ubuntu 20.04 LTS us-west-1 - deprecated
      ImageId: ami-021809d9177640a20 # Ubuntu 20.04 LTS us-west-1
      #ImageId: ami-0502e817a62226e03 # Ubuntu 20.04 LTS eu-central-1
      SubnetId:
        Fn::ImportValue:
              !Sub ${EnvironmentName}-PUB1-SN
      SecurityGroupIds:
        [!GetAtt WebServerSecGroup.GroupId]
      KeyName: WRIEC2

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          add-apt-repository -y ppa:deadsnakes/ppa 
          apt-get update -y

          apt-get install apache2 -y
          systemctl start apache2.service

          apt install python3-pip -y
          pip3 install uvicorn

      InstanceType: t3.medium
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"
        Ebs:
          VolumeSize: '20'
